version: "3"
services:
  app:
    container_name: movie-api
    build: app
    restart: always
    ports:
      - 3333:3000
    volumes:
      - ./app:/app
    links:
      - database
    depends_on:
      - database
  database:
    container_name: movie-db
    image: mongo
    ports:
      - 27017:27017
